import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>DuAcademia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-900 min-h-screen p-10 items-center w-full">
        <div className="max-w-[1000px] mx-auto text-center">
          <h1 className="text-3xl md:text-7xl font-bold text-white">DuAcademia</h1>
          <p className="text-lg text-gray-500 mt-5">
            One stop for all your academic needs
          </p>
          <div className="mt-10">
            <input
              type="text"
              placeholder="Search for resources"
              className="bg-gray-800 p-3 rounded-lg text-gray-500 focus:outline-none focus:shadow-outline"
            />
            <button className="ml-5 bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg">
              Search
            </button>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10 mt-10">
            <div>
              <Image
                className="mx-auto"
                src="/narutoo.png"
                width={50}
                height={50}
                alt="naruto"
              />
              <Link href="/course/bbe">
              <div className="bg-gray-800 flex justify-center items-center h-28 rounded-lg shadow-lg p-5 relative hover:shadow-xl hover:bg-gray-700 transition-shadow duration-200">
                <h3 className="text-4xl font-bold text-white">BBE</h3>
                {/* <p className="text-gray-400 mt-2">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p> */}
              </div>
              </Link>
            </div>
            <div>
              <Image
                className="mx-auto"
                src="/narutoo.png"
                width={50}
                height={50}
                alt="naruto"
              />
              <Link href="/course/bcom">
              <div className="bg-gray-800 flex justify-center items-center h-28 rounded-lg shadow-lg p-5 relative hover:shadow-xl hover:bg-gray-700 transition-shadow duration-200">
                <h3 className="text-4xl font-bold text-white">BCOM</h3>
                {/* <p className="text-gray-400 mt-2">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p> */}
              </div>
              </Link>
            </div>
            
            <div>
              <Image
                className="mx-auto"
                src="/narutoo.png"
                width={50}
                height={50}
                alt="naruto"
              />
              <Link href="/course/ba">
              <div className="bg-gray-800 flex justify-center items-center h-28 rounded-lg shadow-lg p-5 relative hover:shadow-xl hover:bg-gray-700 transition-shadow duration-200">
                <h3 className="text-4xl font-bold text-white">BA PROGRAMME</h3>
                {/* <p className="text-gray-400 mt-2">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p> */}
              </div>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
